/*

❖ Both are used to get the last value generated in the identity
column of the table.

❖ @@IDENTITY function returns the last identity value generated 
within the current session, regardless of the scope. 

❖ This will return a value generated by an INSERT statement in a 
trigger, stored procedure or batch of T-SQL statements.

SELECT @@IDENTITY

❖ The scope_identity() function returns the last identity created in 
the same session and the same scope.

SELECT SCOPE_IDENTITY()

❖ Mostly we use scope_identity() function inside stored procedures.

*/
